version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-1
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin12345
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - docker-db

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-common
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - docker-db
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin12345
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  postgres_data:
  mongodb_data:

networks:
  docker-db:
    name: docker-db


# docker-compose -f docker/db-compose.yaml up
# host: host.docker.internal -> khi connect by pgAdmin web